### ISSUE TITLE
Errors in Cloud Shell TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by Nogbit** [therealcmj/ociextirpater#16]
I get the following error when running this

```
$$$$@cloudshell:ociextirpater (us-ashburn-1)$ ./ociextirpate.py <my compart ocid> -dt
2024-11-15 21:08:34,990 MainThread    INFO ociextirpate:extirpate -> Starting up
2024-11-15 21:08:34,990 MainThread    INFO ociextirpate:extirpate -> Configuring...
Traceback (most recent call last):
  File "./ociextirpate.py", line 59, in <module>
    extirpate()
  File "./ociextirpate.py", line 16, in extirpate
    from ociextirpater.config import config
  File "/home/marcellus_/ociextirpater/ociextirpater/config.py", line 5, in <module>
    class config:
  File "/home/marcellus_/ociextirpater/ociextirpater/config.py", line 156, in config
    def validate(self, cmd: argparse.Namespace) -> tuple[bool, str]:
TypeError: 'type' object is not subscriptable
```

**Comment by therealcmj** [comment]
Sorry about that! @flynnkc  made fix on this just a moment ago. Please pull again and re-test.

**Comment by Nogbit** [comment]
Awesome, thanks.  That worked.
